import { LightningElement, track } from 'lwc';
import getTopReports from '@salesforce/apex/BugHuntLeaderboardController.getTopReports';
import getIsAdmin from '@salesforce/apex/BugHuntLeaderboardController.getIsAdmin';
import clearAllReports from '@salesforce/apex/BugHuntLeaderboardController.clearAllReports';
import deleteReport from '@salesforce/apex/BugHuntLeaderboardController.deleteReport';

export default class BugHuntLeaderboard extends LightningElement {
    @track rows = [];
    @track reporterSummary = [];
    @track showDetails = false;
    @track detailSummary;
    @track detailBefore = [];
    @track detailAfter = [];
    columns = [
        { label: 'Submitted By', fieldName: 'SubmittedBy__c', sortable: true },
        { label: 'Bug Report Description', fieldName: 'Description__c', wrapText: true },
        // Show only the user-input (Before) portion for readability
        { label: 'Details', fieldName: 'DetailsUser__c', wrapText: true },
        { label: 'Case Number', fieldName: 'CaseUrl__c', type: 'url', typeAttributes: { label: { fieldName: 'CaseNumber__c' }, target: '_blank' } },
        { label: 'Created', fieldName: 'CreatedDate', type: 'date', sortable: true, typeAttributes: { year: 'numeric', month: 'short', day: '2-digit', hour: '2-digit', minute: '2-digit' } },
        { type: 'action', typeAttributes: { rowActions: [ { label: 'View Details', name: 'view_details' }, { label: 'Delete', name: 'delete_row' } ] } }
    ];
    @track isAdmin = false;
    @track sortBy = 'CreatedDate';
    @track sortDirection = 'desc';
    @track search = '';

    connectedCallback() {
        this.refresh();
        getIsAdmin().then((v)=>{ this.isAdmin = !!v; }).catch(()=>{ this.isAdmin = false; });
        this.startAutoRefresh();
    }
    disconnectedCallback() {
        this.stopAutoRefresh();
    }

    startAutoRefresh() {
        this.stopAutoRefresh();
        this._timer = window.setInterval(() => this.refresh(), 5000);
    }
    stopAutoRefresh() {
        if (this._timer) {
            window.clearInterval(this._timer);
            this._timer = undefined;
        }
    }

    // Extract values from Details__c fallback text generated by Apex
    parseDetails(details) {
        const out = {};
        if (!details) return out;
        const lines = details.split(/\r?\n/);
    for (const line of lines) {
        const m = line.match(/^\s*(Subject|Origin|Type|Priority|Reason|Description|Email|Urgent|User):\s*(.*)$/i);
            if (m) {
                const key = m[1].toLowerCase();
                const val = (m[2] || '').trim();
                switch (key) {
                    case 'subject': out.Subject__c = val; break;
                    case 'origin': out.Origin__c = val; break;
                    case 'type': out.Type__c = val; break;
                    case 'priority': out.Priority__c = val; break;
                    case 'reason': out.Reason__c = val; break;
                    case 'urgent': out.Urgent__c = /^true$/i.test(val); break;
                    case 'user': out.SubmittedBy__c = val || 'guest'; break;
                    case 'description': out.Description__c = val; break;
                    default: break;
                }
            }
        }
        return out;
    }

    // Parse details formatted as 'Summary---Before (user input)...---After (saved)...'
    parseBeforeAfter(details) {
        if (!details) return { summary: '', before: {}, after: {} };
        const beforeMarker = /---Before\s*\(user input\)/i;
        const afterMarker = /---After\s*\(saved\)/i;
        const bIdx = details.search(beforeMarker);
        const aIdx = details.search(afterMarker);
        const summary = bIdx > 0 ? details.substring(0, bIdx).trim() : '';
        const beforeStart = bIdx >= 0 ? (bIdx + details.match(beforeMarker)[0].length) : 0;
        const beforeEnd = aIdx >= 0 ? aIdx : details.length;
        const beforePart = details.substring(beforeStart, beforeEnd).trim();
        const afterStart = aIdx >= 0 ? (aIdx + details.match(afterMarker)[0].length) : details.length;
        const afterPart = details.substring(afterStart).trim();

        // Extract consecutive key:value tokens even without newlines
        const toMap = (text) => {
            const map = {};
            const keyRe = /(RecordId|Subject|Origin|Type|Priority|Reason|Description|Email|Urgent|User):/gi;
            let m;
            let lastKey = null;
            let lastIndex = 0;
            while ((m = keyRe.exec(text)) !== null) {
                if (lastKey !== null) {
                    const value = text.substring(lastIndex, m.index).trim();
                    map[lastKey] = value;
                }
                lastKey = m[1];
                lastIndex = keyRe.lastIndex;
            }
            if (lastKey !== null) {
                const value = text.substring(lastIndex).trim();
                map[lastKey] = value;
            }
            return map;
        };
        return { summary, before: toMap(beforePart), after: toMap(afterPart) };
    }

    async refresh() {
        try {
            const data = await getTopReports();
            const raw = data || [];

            // First pass: map with fallback from Details__c
            const mapped = raw.map((r) => {
                const f = this.parseDetails(r.Details__c);
                const row = { ...r };
                row.SubmittedBy__c = r.SubmittedBy__c || f.SubmittedBy__c || '';
                // Case link and number
                const caseNumber = r.Case__r && r.Case__r.CaseNumber ? r.Case__r.CaseNumber : '';
                row.CaseNumber__c = caseNumber;
                row.CaseUrl__c = caseNumber ? `https://orgfarm-f0aabc7d37-dev-ed.develop.lightning.force.com/lightning/r/Case/${r.Case__c}/view` : '';
                // Keep full details for modal

                row.FullDetails__c = r.Details__c || '';
                
                const { before } = this.parseBeforeAfter(r.Details__c || '');
                const order = ['Subject', 'Origin', 'Type', 'Priority', 'Reason', 'Description', 'Email', 'Urgent', 'User'];
                const parts = [];
                order.forEach((k) => {
                    const v = before[k];
                    if (v !== undefined && String(v).trim() !== '') parts.push(`${k}: ${v}`);
                });
                const detailsText = parts.join(' | ');
                // Show only the text before the '--- After (saved)' marker in the table
                const aIdx = detailsText.search(/---\s*After\s*\(saved\)/i);
                const trimmed = aIdx >= 0 ? detailsText.substring(0, aIdx).trim() : detailsText;
                row.DetailsUser__c = trimmed;
                return row;
            });

            // Second pass: compute counts per reporter and append to SubmittedBy for quick tracking
            const counts = {};
            for (const r of mapped) {
                const who = (r.SubmittedBy__c || 'guest').trim();
                if (!who) continue;
                counts[who] = (counts[who] || 0) + 1;
            }
            mapped.forEach((r) => {
                const who = (r.SubmittedBy__c || 'guest').trim();
                const cnt = counts[who] || 0;
                if (who) r.SubmittedBy__c = `${who} (${cnt})`;
            });

            // Build a compact summary list for optional display
            const summary = Object.keys(counts)
                .map((name) => ({ name, count: counts[name] }))
                .sort((a, b) => b.count - a.count)
                .slice(0, 10);

            this.reporterSummary = summary;
            this._all = mapped;
            this.applyView();
        } catch (e) {
            // eslint-disable-next-line no-console
            console.error('Failed to load leaderboard', e);
        }
    }

    handleRowAction(event) {
    const actionName = event.detail.action.name;
        const row = event.detail.row;
        if (actionName === 'view_details') {
            try {
        const { summary, before, after } = this.parseBeforeAfter(row.FullDetails__c || row.Details__c || '');
                this.detailSummary = summary || row.Subject__c || 'Bug report';
                this.detailBefore = Object.keys(before).map(k=>({ label: k, value: before[k] }));
                let afterList = Object.keys(after).map(k=>({ label: k, value: after[k] }));
        if (!afterList.length) {
                    // Fallback to record fields as "After"
                    afterList = [
                        { label: 'RecordId', value: row.Case__c || '' },
                        { label: 'Subject', value: row.Subject__c || '' },
                        { label: 'Origin', value: row.Origin__c || '' },
                        { label: 'Type', value: row.Type__c || '' },
                        { label: 'Priority', value: row.Priority__c || '' },
                        { label: 'Reason', value: (row.Case__r && row.Case__r.Reason) || '' },
                        { label: 'Description', value: row.Description__c || '' },
                        { label: 'Email', value: row.Email__c || '' },
                        { label: 'Urgent', value: String(row.Urgent__c) }
                    ];
                }
                this.detailAfter = afterList;
                this.showDetails = true;
                this.stopAutoRefresh();
            } catch (e) {
                // eslint-disable-next-line no-console
                console.error('Failed to open details', e);
                // eslint-disable-next-line no-alert
                alert('Unable to open details for this row.');
            }
        } else if (actionName === 'delete_row') {
            if (!this.isAdmin) {
                // eslint-disable-next-line no-alert
                alert('Not authorized to delete.');
                return;
            }
            // eslint-disable-next-line no-alert
            const ok = confirm('Delete this bug report?');
            if (!ok) return;
            deleteReport({ reportId: row.Id })
                .then(()=> this.refresh())
                .catch((e)=>{
                    // eslint-disable-next-line no-console
                    console.error('Delete failed', e);
                    // eslint-disable-next-line no-alert
                    alert('Delete failed');
                });
        }
    }

    closeDetails() { 
        this.showDetails = false; 
        this.startAutoRefresh();
    }

    applyView() {
        let rows = [...(this._all || [])];
        const q = (this.search || '').trim().toLowerCase();
        if (q) {
            rows = rows.filter(r =>
                (r.SubmittedBy__c||'').toLowerCase().includes(q) ||
                (r.Description__c||'').toLowerCase().includes(q) ||
                (r.Details__c||'').toLowerCase().includes(q) ||
                (r.CaseNumber__c||'').toLowerCase().includes(q)
            );
        }
        const dir = this.sortDirection === 'desc' ? -1 : 1;
        const key = this.sortBy;
        rows.sort((a,b)=>{
            const va = (a[key]||'').toString().toLowerCase();
            const vb = (b[key]||'').toString().toLowerCase();
            if (va<vb) return -1*dir; if (va>vb) return 1*dir; return 0;
        });
        this.rows = rows;
    }

    handleSort(event) {
        this.sortBy = event.detail.fieldName;
        this.sortDirection = event.detail.sortDirection;
        this.applyView();
    }
    handleSearch(event) {
        this.search = event.target.value;
        this.applyView();
    }
    async handleClear() {
        if (!this.isAdmin) return;
        try {
            const deleted = await clearAllReports();
            // eslint-disable-next-line no-alert
            alert(`Deleted ${deleted} bug reports`);
            this.refresh();
        } catch (e) {
            // eslint-disable-next-line no-console
            console.error('Failed to clear reports', e);
        }
    }
}
